version: '3.7'

services:
  db:
    image: postgres:alpine
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  back:
    image: kurovale/kuro-tweet
    environment:
      DATABASE_URL: postgresql://postgres:pass@db:5432/postgres
      JWT_SECRET: veryVerySecret
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
  front:
    build: ./
    depends_on: [ back ]
    ports:
      - "3000:80"
